cert-manager:
  enabled: true
  cluster-issuer:
    create: false
    provider: self-signed
    name: selfsigned-cluster-issuer
  email: mail@example.net

kcm:
  namespace: kcm-system
  installTemplates: true
  kof:
    repo:
      name: kof
      spec:
        type: oci
        url: oci://10.244.0.1:30500/k0rdent/kof/charts

victoria-metrics-operator:
  watchNamespaces: ["kof"]

grafana:
  enabled: true
  ingress:
    enabled: true
    host: grafana.pzimmer-kof6.cso-k0rdent-lab-team.eu-cloud.mirantis.net
  security:
    credentials_secret_name: grafana-mothership-admin-credentials
  alerts:
    enabled: true
defaultRules:
  rules:
    CapiControllerDown:
      create: false
    Watchdog:
      create: true
      spec:
        labels:
          severity: info
          service: kof
          host: alertmanager
          subject: '[INFORMATIONAL] Watchdog'

#  groups:
#    control-plane-alerts:
#      create: true
victoriametrics:
  vmalert:
    enabled: true
    remoteRead: ""
    extraArgs:
      externalURL: 'https://grafana.example.com'
      externalAlertSource: 'alerting/groups?groupBy=alertname&queryString=urlencoded(join(‘ ’,labelname=labelvalue))'
    vmalertmanager:
      externalURL: "https://grafana.example.com"
      config: |
        global:
          resolve_timeout: 5m
        route:
          receiver: Salesforce
          routes:
          - receiver: Salesforce
            matchers:
            - alertname="Watchdog"
          - receiver: blackhole
            matchers:
            - severity=~"info|warning"
        receivers:
          - name: Salesforce
            webhook_configs:
              - send_resolved: true
                http_config:
                  follow_redirects: true
                  enable_http2: true
                url: 'http://sf-notifier:5000/hook'
                max_alerts: 0
          - name: blackhole

